# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff93caccb77508b4d3706c85f1e16f0b06dd3f151104dbf81b7b1489a3c370ca3588ae74f88ad7b53870d54f5ac9991000e965b253928e3e5a59e9ae2dbe7b07

test:
  secret_key_base: 7d191e3f8f329bcc88d66c100d1a07f91d1471a07b78ad1b66fd8203cb02c149d880ff02f56e4b12a46bfefac523304c42b9add7fc8b808ac0bc9b784510a89f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
